"""
Seed script for achievements.

Run with: python -m scripts.seed_achievements
"""

import asyncio

from sqlalchemy import select

from db.session import async_session_maker
from models.achievement import Achievement

ACHIEVEMENTS = [
    # === VOTING ACHIEVEMENTS ===
    {
        "id": "first_vote",
        "name": "First Vote",
        "description": "Cast your first vote and make your voice heard",
        "icon": "🗳️",
        "action_type": "vote",
        "target_count": 1,
        "points_reward": 50,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "voting",
        "sort_order": 1,
    },
    {
        "id": "votes_10",
        "name": "Getting Started",
        "description": "Cast 10 votes",
        "icon": "✅",
        "action_type": "vote",
        "target_count": 10,
        "points_reward": 100,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "voting",
        "sort_order": 2,
    },
    {
        "id": "votes_50",
        "name": "Active Citizen",
        "description": "Cast 50 votes",
        "icon": "🏛️",
        "action_type": "vote",
        "target_count": 50,
        "points_reward": 250,
        "is_repeatable": False,
        "tier": "silver",
        "category": "voting",
        "sort_order": 3,
    },
    {
        "id": "votes_100",
        "name": "Century Voter",
        "description": "Cast 100 votes",
        "icon": "💯",
        "action_type": "vote",
        "target_count": 100,
        "points_reward": 500,
        "is_repeatable": False,
        "tier": "gold",
        "category": "voting",
        "sort_order": 4,
    },
    {
        "id": "votes_500",
        "name": "Voice of the People",
        "description": "Cast 500 votes",
        "icon": "📢",
        "action_type": "vote",
        "target_count": 500,
        "points_reward": 1000,
        "is_repeatable": False,
        "tier": "platinum",
        "category": "voting",
        "sort_order": 5,
    },
    # === STREAK ACHIEVEMENTS ===
    {
        "id": "streak_3",
        "name": "Getting Consistent",
        "description": "Vote 3 days in a row",
        "icon": "🔥",
        "action_type": "streak",
        "target_count": 3,
        "points_reward": 50,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "streak",
        "sort_order": 10,
    },
    {
        "id": "streak_7",
        "name": "Week Warrior",
        "description": "Vote 7 days in a row",
        "icon": "🔥",
        "action_type": "streak",
        "target_count": 7,
        "points_reward": 200,
        "is_repeatable": False,
        "tier": "silver",
        "category": "streak",
        "sort_order": 11,
    },
    {
        "id": "streak_14",
        "name": "Two Week Champion",
        "description": "Vote 14 days in a row",
        "icon": "⚡",
        "action_type": "streak",
        "target_count": 14,
        "points_reward": 350,
        "is_repeatable": False,
        "tier": "silver",
        "category": "streak",
        "sort_order": 12,
    },
    {
        "id": "streak_30",
        "name": "Monthly Devotee",
        "description": "Vote 30 days in a row",
        "icon": "⚡",
        "action_type": "streak",
        "target_count": 30,
        "points_reward": 500,
        "is_repeatable": False,
        "tier": "gold",
        "category": "streak",
        "sort_order": 13,
    },
    {
        "id": "streak_90",
        "name": "Quarterly Legend",
        "description": "Vote 90 days in a row",
        "icon": "👑",
        "action_type": "streak",
        "target_count": 90,
        "points_reward": 1500,
        "is_repeatable": False,
        "tier": "platinum",
        "category": "streak",
        "sort_order": 14,
    },
    {
        "id": "streak_365",
        "name": "Year-Round Voter",
        "description": "Vote every day for a year",
        "icon": "🏆",
        "action_type": "streak",
        "target_count": 365,
        "points_reward": 5000,
        "is_repeatable": False,
        "tier": "platinum",
        "category": "streak",
        "sort_order": 15,
    },
    # === PROFILE ACHIEVEMENTS ===
    {
        "id": "profile_complete",
        "name": "Identity Established",
        "description": "Complete your demographic profile (8+ fields)",
        "icon": "👤",
        "action_type": "profile",
        "target_count": 8,
        "points_reward": 100,
        "is_repeatable": False,
        "tier": "silver",
        "category": "profile",
        "sort_order": 20,
    },
    # === VERIFICATION ACHIEVEMENTS ===
    {
        "id": "email_verified",
        "name": "Email Confirmed",
        "description": "Verify your email address",
        "icon": "📧",
        "action_type": "verify_email",
        "target_count": 1,
        "points_reward": 25,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "verification",
        "sort_order": 21,
    },
    {
        "id": "phone_verified",
        "name": "Phone Confirmed",
        "description": "Verify your phone number",
        "icon": "📱",
        "action_type": "verify_phone",
        "target_count": 1,
        "points_reward": 50,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "verification",
        "sort_order": 22,
    },
    {
        "id": "fully_verified",
        "name": "Verified Voter",
        "description": "Complete both email and phone verification",
        "icon": "✅",
        "action_type": "verify_full",
        "target_count": 1,
        "points_reward": 100,
        "is_repeatable": False,
        "tier": "silver",
        "category": "verification",
        "sort_order": 23,
    },
    # === DAILY LEADERBOARD ACHIEVEMENTS (Repeatable) ===
    {
        "id": "daily_rank_1",
        "name": "Daily Champion",
        "description": "Rank #1 on the daily leaderboard",
        "icon": "🥇",
        "action_type": "leaderboard_daily",
        "target_count": 1,
        "points_reward": 500,
        "is_repeatable": True,
        "tier": "gold",
        "category": "leaderboard",
        "sort_order": 30,
    },
    {
        "id": "daily_rank_2",
        "name": "Daily Runner-Up",
        "description": "Rank #2 on the daily leaderboard",
        "icon": "🥈",
        "action_type": "leaderboard_daily",
        "target_count": 2,
        "points_reward": 300,
        "is_repeatable": True,
        "tier": "silver",
        "category": "leaderboard",
        "sort_order": 31,
    },
    {
        "id": "daily_rank_3",
        "name": "Daily Bronze",
        "description": "Rank #3 on the daily leaderboard",
        "icon": "🥉",
        "action_type": "leaderboard_daily",
        "target_count": 3,
        "points_reward": 200,
        "is_repeatable": True,
        "tier": "bronze",
        "category": "leaderboard",
        "sort_order": 32,
    },
    # === MONTHLY LEADERBOARD ACHIEVEMENTS (Repeatable) ===
    {
        "id": "monthly_rank_1",
        "name": "Monthly Champion",
        "description": "Rank #1 on the monthly leaderboard",
        "icon": "🏆",
        "action_type": "leaderboard_monthly",
        "target_count": 1,
        "points_reward": 2000,
        "is_repeatable": True,
        "tier": "platinum",
        "category": "leaderboard",
        "sort_order": 40,
    },
    {
        "id": "monthly_rank_2",
        "name": "Monthly Runner-Up",
        "description": "Rank #2 on the monthly leaderboard",
        "icon": "🥈",
        "action_type": "leaderboard_monthly",
        "target_count": 2,
        "points_reward": 1000,
        "is_repeatable": True,
        "tier": "gold",
        "category": "leaderboard",
        "sort_order": 41,
    },
    {
        "id": "monthly_rank_3",
        "name": "Monthly Bronze",
        "description": "Rank #3 on the monthly leaderboard",
        "icon": "🥉",
        "action_type": "leaderboard_monthly",
        "target_count": 3,
        "points_reward": 500,
        "is_repeatable": True,
        "tier": "silver",
        "category": "leaderboard",
        "sort_order": 42,
    },
    # === YEARLY LEADERBOARD ACHIEVEMENTS (Repeatable) ===
    {
        "id": "yearly_rank_1",
        "name": "Annual Champion",
        "description": "Rank #1 on the yearly leaderboard",
        "icon": "👑",
        "action_type": "leaderboard_yearly",
        "target_count": 1,
        "points_reward": 10000,
        "is_repeatable": True,
        "tier": "platinum",
        "category": "leaderboard",
        "sort_order": 50,
    },
    {
        "id": "yearly_rank_2",
        "name": "Annual Runner-Up",
        "description": "Rank #2 on the yearly leaderboard",
        "icon": "🥈",
        "action_type": "leaderboard_yearly",
        "target_count": 2,
        "points_reward": 5000,
        "is_repeatable": True,
        "tier": "gold",
        "category": "leaderboard",
        "sort_order": 51,
    },
    {
        "id": "yearly_rank_3",
        "name": "Annual Bronze",
        "description": "Rank #3 on the yearly leaderboard",
        "icon": "🥉",
        "action_type": "leaderboard_yearly",
        "target_count": 3,
        "points_reward": 2500,
        "is_repeatable": True,
        "tier": "silver",
        "category": "leaderboard",
        "sort_order": 52,
    },
    # === DEMOGRAPHIC POINT ACHIEVEMENTS ===
    {
        "id": "demo_age",
        "name": "Age Shared",
        "description": "Share your age range for better insights",
        "icon": "📊",
        "action_type": "demographic",
        "target_count": 1,
        "points_reward": 150,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "profile",
        "sort_order": 21,
    },
    {
        "id": "demo_gender",
        "name": "Gender Shared",
        "description": "Share your gender for better insights",
        "icon": "📊",
        "action_type": "demographic",
        "target_count": 1,
        "points_reward": 100,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "profile",
        "sort_order": 22,
    },
    {
        "id": "demo_location",
        "name": "Location Shared",
        "description": "Share your country for better insights",
        "icon": "🌍",
        "action_type": "demographic",
        "target_count": 1,
        "points_reward": 150,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "profile",
        "sort_order": 23,
    },
    {
        "id": "demo_geo_detailed",
        "name": "Geo Details Shared",
        "description": "Share your state/province and city",
        "icon": "📍",
        "action_type": "demographic",
        "target_count": 1,
        "points_reward": 225,
        "is_repeatable": False,
        "tier": "silver",
        "category": "profile",
        "sort_order": 24,
    },
    {
        "id": "demo_education",
        "name": "Education Shared",
        "description": "Share your education level for better insights",
        "icon": "🎓",
        "action_type": "demographic",
        "target_count": 1,
        "points_reward": 150,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "profile",
        "sort_order": 25,
    },
    {
        "id": "demo_employment",
        "name": "Employment Shared",
        "description": "Share your employment status for better insights",
        "icon": "💼",
        "action_type": "demographic",
        "target_count": 1,
        "points_reward": 125,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "profile",
        "sort_order": 26,
    },
    {
        "id": "demo_political",
        "name": "Political Leaning Shared",
        "description": "Share your political leaning (highest points for sensitive data)",
        "icon": "🏛️",
        "action_type": "demographic",
        "target_count": 1,
        "points_reward": 200,
        "is_repeatable": False,
        "tier": "silver",
        "category": "profile",
        "sort_order": 27,
    },
    # New demographic achievements
    {
        "id": "demo_marital",
        "name": "Marital Status Shared",
        "description": "Share your marital status for better insights",
        "icon": "💍",
        "action_type": "demographic",
        "target_count": 1,
        "points_reward": 125,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "profile",
        "sort_order": 28,
    },
    {
        "id": "demo_religion",
        "name": "Religious Affiliation Shared",
        "description": "Share your religious affiliation (higher points for sensitive data)",
        "icon": "🙏",
        "action_type": "demographic",
        "target_count": 1,
        "points_reward": 175,
        "is_repeatable": False,
        "tier": "silver",
        "category": "profile",
        "sort_order": 29,
    },
    {
        "id": "demo_ethnicity",
        "name": "Ethnicity Shared",
        "description": "Share your ethnic background (higher points for sensitive data)",
        "icon": "🌍",
        "action_type": "demographic",
        "target_count": 1,
        "points_reward": 175,
        "is_repeatable": False,
        "tier": "silver",
        "category": "profile",
        "sort_order": 30,
    },
    {
        "id": "demo_income",
        "name": "Household Income Shared",
        "description": "Share your household income range (highest points for financial info)",
        "icon": "💰",
        "action_type": "demographic",
        "target_count": 1,
        "points_reward": 200,
        "is_repeatable": False,
        "tier": "silver",
        "category": "profile",
        "sort_order": 31,
    },
    {
        "id": "demo_parental",
        "name": "Parental Status Shared",
        "description": "Share your parental status for better insights",
        "icon": "👨‍👩‍👧",
        "action_type": "demographic",
        "target_count": 1,
        "points_reward": 100,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "profile",
        "sort_order": 32,
    },
    {
        "id": "demo_housing",
        "name": "Housing Status Shared",
        "description": "Share your housing status for better insights",
        "icon": "🏠",
        "action_type": "demographic",
        "target_count": 1,
        "points_reward": 100,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "profile",
        "sort_order": 33,
    },
    {
        "id": "demo_complete_extended",
        "name": "Full Profile Achieved",
        "description": "Complete your full demographic profile (14+ fields)",
        "icon": "⭐",
        "action_type": "profile",
        "target_count": 14,
        "points_reward": 500,
        "is_repeatable": False,
        "tier": "gold",
        "category": "profile",
        "sort_order": 34,
    },
    # === SHARING ACHIEVEMENTS ===
    # Designed to drive viral growth and platform adoption
    {
        "id": "first_share",
        "name": "Spreading the Word",
        "description": "Share a poll or achievement for the first time",
        "icon": "📣",
        "action_type": "share",
        "target_count": 1,
        "points_reward": 25,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "sharing",
        "sort_order": 40,
    },
    {
        "id": "shares_10",
        "name": "Social Butterfly",
        "description": "Share content 10 times across any platform",
        "icon": "🦋",
        "action_type": "share",
        "target_count": 10,
        "points_reward": 100,
        "is_repeatable": False,
        "tier": "silver",
        "category": "sharing",
        "sort_order": 41,
    },
    {
        "id": "shares_50",
        "name": "Influencer",
        "description": "Share content 50 times - you're helping TruePulse grow!",
        "icon": "🌟",
        "action_type": "share",
        "target_count": 50,
        "points_reward": 300,
        "is_repeatable": False,
        "tier": "gold",
        "category": "sharing",
        "sort_order": 42,
    },
    {
        "id": "shares_100",
        "name": "Ambassador",
        "description": "Share content 100 times - you're a true TruePulse ambassador!",
        "icon": "👑",
        "action_type": "share",
        "target_count": 100,
        "points_reward": 500,
        "is_repeatable": False,
        "tier": "platinum",
        "category": "sharing",
        "sort_order": 43,
    },
    # Platform-specific sharing achievements for cross-platform reach
    {
        "id": "share_twitter",
        "name": "X/Twitter Pioneer",
        "description": "Share content to X/Twitter for the first time",
        "icon": "🐦",
        "action_type": "share_platform",
        "target_count": 1,
        "points_reward": 15,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "sharing",
        "sort_order": 44,
    },
    {
        "id": "share_facebook",
        "name": "Facebook Connector",
        "description": "Share content to Facebook for the first time",
        "icon": "👍",
        "action_type": "share_platform",
        "target_count": 1,
        "points_reward": 15,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "sharing",
        "sort_order": 45,
    },
    {
        "id": "share_linkedin",
        "name": "LinkedIn Networker",
        "description": "Share content to LinkedIn for the first time",
        "icon": "💼",
        "action_type": "share_platform",
        "target_count": 1,
        "points_reward": 15,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "sharing",
        "sort_order": 46,
    },
    {
        "id": "share_reddit",
        "name": "Reddit Explorer",
        "description": "Share content to Reddit for the first time",
        "icon": "🤖",
        "action_type": "share_platform",
        "target_count": 1,
        "points_reward": 15,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "sharing",
        "sort_order": 47,
    },
    {
        "id": "share_whatsapp",
        "name": "WhatsApp Messenger",
        "description": "Share content to WhatsApp for the first time",
        "icon": "💬",
        "action_type": "share_platform",
        "target_count": 1,
        "points_reward": 15,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "sharing",
        "sort_order": 48,
    },
    {
        "id": "share_telegram",
        "name": "Telegram Broadcaster",
        "description": "Share content to Telegram for the first time",
        "icon": "✈️",
        "action_type": "share_platform",
        "target_count": 1,
        "points_reward": 15,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "sharing",
        "sort_order": 49,
    },
    {
        "id": "share_all_platforms",
        "name": "Cross-Platform Champion",
        "description": "Share content to all 6 social platforms at least once",
        "icon": "🌐",
        "action_type": "share_all_platforms",
        "target_count": 6,
        "points_reward": 200,
        "is_repeatable": False,
        "tier": "gold",
        "category": "sharing",
        "sort_order": 50,
    },
    # === AD ENGAGEMENT ACHIEVEMENTS (Support TruePulse) ===
    {
        "id": "ad_supporter_first",
        "name": "Supporter",
        "description": "View your first ad and help support TruePulse",
        "icon": "💝",
        "action_type": "ad_view",
        "target_count": 1,
        "points_reward": 25,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "support",
        "sort_order": 60,
    },
    {
        "id": "ad_views_10",
        "name": "Community Builder",
        "description": "View 10 ads to help keep TruePulse free",
        "icon": "🏠",
        "action_type": "ad_view",
        "target_count": 10,
        "points_reward": 50,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "support",
        "sort_order": 61,
    },
    {
        "id": "ad_views_50",
        "name": "Platform Champion",
        "description": "View 50 ads - you're making a real difference!",
        "icon": "🏆",
        "action_type": "ad_view",
        "target_count": 50,
        "points_reward": 150,
        "is_repeatable": False,
        "tier": "silver",
        "category": "support",
        "sort_order": 62,
    },
    {
        "id": "ad_views_100",
        "name": "TruePulse Sustainer",
        "description": "View 100 ads - thank you for keeping democracy accessible!",
        "icon": "💎",
        "action_type": "ad_view",
        "target_count": 100,
        "points_reward": 300,
        "is_repeatable": False,
        "tier": "gold",
        "category": "support",
        "sort_order": 63,
    },
    {
        "id": "ad_click_curious",
        "name": "Curious Explorer",
        "description": "Click on your first ad to learn more",
        "icon": "🔍",
        "action_type": "ad_click",
        "target_count": 1,
        "points_reward": 30,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "support",
        "sort_order": 64,
    },
    {
        "id": "ad_clicks_10",
        "name": "Active Supporter",
        "description": "Click on 10 ads - your engagement helps fund TruePulse",
        "icon": "👆",
        "action_type": "ad_click",
        "target_count": 10,
        "points_reward": 100,
        "is_repeatable": False,
        "tier": "silver",
        "category": "support",
        "sort_order": 65,
    },
    {
        "id": "ad_clicks_25",
        "name": "Patron of Truth",
        "description": "Click on 25 ads - you're a true patron of TruePulse",
        "icon": "🌟",
        "action_type": "ad_click",
        "target_count": 25,
        "points_reward": 250,
        "is_repeatable": False,
        "tier": "gold",
        "category": "support",
        "sort_order": 66,
    },
    {
        "id": "daily_supporter",
        "name": "Daily Supporter",
        "description": "View at least one ad every day for a week",
        "icon": "📅",
        "action_type": "ad_streak",
        "target_count": 7,
        "points_reward": 100,
        "is_repeatable": True,
        "tier": "silver",
        "category": "support",
        "sort_order": 67,
    },
    # === PULSE POLL ACHIEVEMENTS ===
    {
        "id": "pulse_first",
        "name": "First Pulse",
        "description": "Vote in your first daily Pulse Poll",
        "icon": "💓",
        "action_type": "pulse_vote",
        "target_count": 1,
        "points_reward": 50,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "pulse",
        "sort_order": 70,
    },
    {
        "id": "pulse_10",
        "name": "Pulse Regular",
        "description": "Vote in 10 daily Pulse Polls",
        "icon": "💗",
        "action_type": "pulse_vote",
        "target_count": 10,
        "points_reward": 150,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "pulse",
        "sort_order": 71,
    },
    {
        "id": "pulse_30",
        "name": "Pulse Devotee",
        "description": "Vote in 30 daily Pulse Polls",
        "icon": "💖",
        "action_type": "pulse_vote",
        "target_count": 30,
        "points_reward": 300,
        "is_repeatable": False,
        "tier": "silver",
        "category": "pulse",
        "sort_order": 72,
    },
    {
        "id": "pulse_100",
        "name": "Pulse Master",
        "description": "Vote in 100 daily Pulse Polls",
        "icon": "💝",
        "action_type": "pulse_vote",
        "target_count": 100,
        "points_reward": 750,
        "is_repeatable": False,
        "tier": "gold",
        "category": "pulse",
        "sort_order": 73,
    },
    {
        "id": "pulse_365",
        "name": "Year of Pulse",
        "description": "Vote in 365 daily Pulse Polls",
        "icon": "❤️‍🔥",
        "action_type": "pulse_vote",
        "target_count": 365,
        "points_reward": 2000,
        "is_repeatable": False,
        "tier": "platinum",
        "category": "pulse",
        "sort_order": 74,
    },
    # Pulse Poll Streaks
    {
        "id": "pulse_streak_7",
        "name": "Weekly Pulse",
        "description": "Vote in Pulse Polls 7 days in a row",
        "icon": "📆",
        "action_type": "pulse_streak",
        "target_count": 7,
        "points_reward": 100,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "pulse",
        "sort_order": 75,
    },
    {
        "id": "pulse_streak_30",
        "name": "Monthly Pulse",
        "description": "Vote in Pulse Polls 30 days in a row",
        "icon": "🗓️",
        "action_type": "pulse_streak",
        "target_count": 30,
        "points_reward": 500,
        "is_repeatable": False,
        "tier": "silver",
        "category": "pulse",
        "sort_order": 76,
    },
    {
        "id": "pulse_streak_90",
        "name": "Quarterly Pulse",
        "description": "Vote in Pulse Polls 90 days in a row",
        "icon": "📊",
        "action_type": "pulse_streak",
        "target_count": 90,
        "points_reward": 1500,
        "is_repeatable": False,
        "tier": "gold",
        "category": "pulse",
        "sort_order": 77,
    },
    {
        "id": "pulse_streak_365",
        "name": "Pulse Legend",
        "description": "Vote in Pulse Polls 365 days in a row - a full year!",
        "icon": "🏆",
        "action_type": "pulse_streak",
        "target_count": 365,
        "points_reward": 5000,
        "is_repeatable": False,
        "tier": "platinum",
        "category": "pulse",
        "sort_order": 78,
    },
    # === FLASH POLL ACHIEVEMENTS ===
    {
        "id": "flash_first",
        "name": "Flash Voter",
        "description": "Vote in your first Flash Poll",
        "icon": "⚡",
        "action_type": "flash_vote",
        "target_count": 1,
        "points_reward": 30,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "flash",
        "sort_order": 80,
    },
    {
        "id": "flash_10",
        "name": "Flash Fan",
        "description": "Vote in 10 Flash Polls",
        "icon": "🌩️",
        "action_type": "flash_vote",
        "target_count": 10,
        "points_reward": 100,
        "is_repeatable": False,
        "tier": "bronze",
        "category": "flash",
        "sort_order": 81,
    },
    {
        "id": "flash_50",
        "name": "Flash Enthusiast",
        "description": "Vote in 50 Flash Polls",
        "icon": "⚡️",
        "action_type": "flash_vote",
        "target_count": 50,
        "points_reward": 300,
        "is_repeatable": False,
        "tier": "silver",
        "category": "flash",
        "sort_order": 82,
    },
    {
        "id": "flash_100",
        "name": "Flash Master",
        "description": "Vote in 100 Flash Polls",
        "icon": "🔥",
        "action_type": "flash_vote",
        "target_count": 100,
        "points_reward": 600,
        "is_repeatable": False,
        "tier": "gold",
        "category": "flash",
        "sort_order": 83,
    },
    {
        "id": "flash_500",
        "name": "Flash Legend",
        "description": "Vote in 500 Flash Polls",
        "icon": "⭐",
        "action_type": "flash_vote",
        "target_count": 500,
        "points_reward": 2000,
        "is_repeatable": False,
        "tier": "platinum",
        "category": "flash",
        "sort_order": 84,
    },
    # Flash Poll speed achievements
    {
        "id": "flash_early_5",
        "name": "Early Responder",
        "description": "Vote in 5 Flash Polls within the first 10 minutes",
        "icon": "🚀",
        "action_type": "flash_early",
        "target_count": 5,
        "points_reward": 150,
        "is_repeatable": False,
        "tier": "silver",
        "category": "flash",
        "sort_order": 85,
    },
    {
        "id": "flash_early_25",
        "name": "First Responder",
        "description": "Vote in 25 Flash Polls within the first 10 minutes",
        "icon": "🏃",
        "action_type": "flash_early",
        "target_count": 25,
        "points_reward": 500,
        "is_repeatable": False,
        "tier": "gold",
        "category": "flash",
        "sort_order": 86,
    },
    # Daily flash poll achievements
    {
        "id": "flash_daily_3",
        "name": "Flash Trio",
        "description": "Vote in 3 Flash Polls in a single day",
        "icon": "3️⃣",
        "action_type": "flash_daily",
        "target_count": 3,
        "points_reward": 50,
        "is_repeatable": True,
        "tier": "bronze",
        "category": "flash",
        "sort_order": 87,
    },
    {
        "id": "flash_daily_5",
        "name": "Flash Five",
        "description": "Vote in 5 Flash Polls in a single day",
        "icon": "5️⃣",
        "action_type": "flash_daily",
        "target_count": 5,
        "points_reward": 100,
        "is_repeatable": True,
        "tier": "silver",
        "category": "flash",
        "sort_order": 88,
    },
    {
        "id": "flash_daily_all",
        "name": "Flash Completionist",
        "description": "Vote in every Flash Poll of the day (at least 8)",
        "icon": "✨",
        "action_type": "flash_daily",
        "target_count": 8,
        "points_reward": 200,
        "is_repeatable": True,
        "tier": "gold",
        "category": "flash",
        "sort_order": 89,
    },
]


async def seed_achievements():
    """Seed achievements into the database."""
    async with async_session_maker() as session:
        for achievement_data in ACHIEVEMENTS:
            # Check if achievement already exists
            result = await session.execute(
                select(Achievement).where(Achievement.id == achievement_data["id"])
            )
            existing = result.scalar_one_or_none()

            if existing:
                # Update existing achievement
                for key, value in achievement_data.items():
                    setattr(existing, key, value)
                print(f"Updated achievement: {achievement_data['id']}")
            else:
                # Create new achievement
                achievement = Achievement(**achievement_data)
                session.add(achievement)
                print(f"Created achievement: {achievement_data['id']}")

        await session.commit()
        print(f"\nSeeded {len(ACHIEVEMENTS)} achievements successfully!")


if __name__ == "__main__":
    asyncio.run(seed_achievements())
