"""
AI Poll Generator Service

Uses Microsoft Foundry (formerly Azure AI Foundry) with Agent Framework
to generate unbiased poll questions from current events.
"""

from datetime import datetime, timedelta, timezone
from typing import TYPE_CHECKING, Any, Optional
from uuid import uuid4

import structlog
from pydantic import BaseModel

from ai.event_aggregator import NewsEvent
from core.config import settings
from schemas.poll import Poll, PollChoice

if TYPE_CHECKING:
    from azure.ai.projects.aio import AIProjectClient
    from azure.identity.aio import DefaultAzureCredential

logger = structlog.get_logger(__name__)


class GeneratedPoll(BaseModel):
    """A poll generated by the AI system."""

    question: str
    choices: list[str]
    category: str
    source_event_id: str
    bias_check_passed: bool
    bias_analysis: dict
    suggested_duration_hours: int


class PollGenerator:
    """
    AI-powered poll generator using Microsoft Agent Framework.

    Generates unbiased poll questions from current events by:
    1. Analyzing multiple perspectives on an event
    2. Generating neutral question framing
    3. Creating balanced answer choices
    4. Performing bias detection and correction

    Uses the Agent Framework with Microsoft Foundry for
    production-grade AI capabilities.
    """

    SYSTEM_PROMPT = """You are an expert pollster and political scientist tasked with
creating unbiased, fair poll questions from current events. Your goals are:

1. NEUTRALITY: Questions must not favor any political party, ideology, or outcome
2. CLARITY: Questions must be clear and unambiguous
3. BALANCE: Answer choices must represent all major viewpoints fairly
4. INCLUSIVITY: Include "Undecided" or "Other" options when appropriate
5. NON-LEADING: Avoid loaded language or presuppositions
6. BROAD RELEVANCE: Focus on topics with national or international significance

IMPORTANT - TOPIC SELECTION CRITERIA:
- PRIORITIZE stories that affect large populations (national policy, international relations, major economic trends)
- PREFER topics that most people can form an opinion on regardless of location
- AVOID hyper-local stories (city council decisions, local crime, regional weather)
- AVOID niche financial news (individual stock earnings, specific company quarterly results)
- FOCUS ON: Policy debates, social issues, technology impacts, global events, public health, environment

When generating polls:
- Frame questions objectively without emotional language
- Present all sides of an issue fairly
- Avoid false dichotomies - include nuanced options
- Don't assume the reader's position
- Use neutral, professional language
- Make questions accessible to a general audience (avoid jargon)

Output format:
{
    "question": "The poll question",
    "choices": ["Choice 1", "Choice 2", "Choice 3", ...],
    "category": "Category name",
    "bias_analysis": {
        "potential_issues": [],
        "mitigations_applied": [],
        "confidence_score": 0.95
    }
}"""

    def __init__(self) -> None:
        self._agent: Any = None
        self._initialized: bool = False
        self._client: Optional["AIProjectClient"] = None
        self._openai_client: Any = None  # Can be AsyncOpenAI or AsyncAzureOpenAI
        self._credential: Optional["DefaultAzureCredential"] = None

    async def initialize(self) -> None:
        """Initialize the AI agent for poll generation."""
        if self._initialized:
            return

        # Try Azure AI Foundry first, then fall back to direct Azure OpenAI
        if settings.FOUNDRY_PROJECT_ENDPOINT:
            try:
                # Import Azure AI Projects SDK components
                from azure.ai.projects.aio import AIProjectClient
                from azure.identity.aio import DefaultAzureCredential

                self._credential = DefaultAzureCredential()
                self._client = AIProjectClient(
                    endpoint=settings.FOUNDRY_PROJECT_ENDPOINT,
                    credential=self._credential,
                )

                # Get OpenAI client for chat completions
                # Note: get_openai_client() is not a coroutine, it returns AsyncOpenAI directly
                self._openai_client = self._client.get_openai_client()

                self._initialized = True
                logger.info("Poll generator initialized with Azure AI Foundry")
                return

            except ImportError:
                logger.warning("Azure AI Projects not installed, trying direct Azure OpenAI")
            except Exception as e:
                logger.warning(f"Failed to initialize Foundry client: {e}, trying direct Azure OpenAI")

        # Fall back to direct Azure OpenAI
        if settings.AZURE_OPENAI_ENDPOINT and settings.AZURE_OPENAI_API_KEY:
            try:
                from openai import AsyncAzureOpenAI

                self._openai_client = AsyncAzureOpenAI(
                    azure_endpoint=settings.AZURE_OPENAI_ENDPOINT,
                    api_key=settings.AZURE_OPENAI_API_KEY,
                    api_version="2024-02-15-preview",
                )
                self._initialized = True
                logger.info("Poll generator initialized with direct Azure OpenAI")
                return

            except ImportError:
                logger.warning("openai package not installed")
            except Exception as e:
                logger.error(f"Failed to initialize Azure OpenAI client: {e}")

        logger.warning("No AI endpoint configured, using mock mode")
        self._initialized = True

    async def generate_poll_from_event(
        self,
        event: NewsEvent,
        context: dict | None = None,
    ) -> GeneratedPoll | None:
        """
        Generate an unbiased poll question from a news event.

        Args:
            event: The news event to generate a poll from
            context: Additional context including diverse perspectives

        Returns:
            A generated poll or None if generation failed
        """
        await self.initialize()

        # Get scope info if available
        scope_info = ""
        if hasattr(event, "scope"):
            scope_info = f"\nGEOGRAPHIC SCOPE: {event.scope.value}"

        # Build the prompt
        prompt = f"""Generate an unbiased poll question based on this news event:

HEADLINE: {event.title}

SUMMARY: {event.summary}

CATEGORY: {event.category}

KEYWORDS: {", ".join(event.keywords)}{scope_info}

{f"ADDITIONAL CONTEXT: {context}" if context else ""}

Create a poll that:
1. Captures the key question the public might have about this event
2. Offers balanced answer choices representing different viewpoints
3. Uses neutral, non-leading language
4. Includes 3-5 answer choices
5. Is relevant to a NATIONAL or INTERNATIONAL audience (avoid hyper-local framing)
6. Focuses on the broader implications, not just the specific event

If this event is too local/niche for a general audience, reframe the question around the broader issue it represents.

Return your response as JSON."""

        try:
            # For development or when AI is not configured, use mock data
            if not self._openai_client:
                return self._generate_mock_poll(event)

            # Use OpenAI client for chat completions
            model = settings.AZURE_OPENAI_DEPLOYMENT or settings.FOUNDRY_MODEL_DEPLOYMENT or "gpt-4o-mini"
            response = await self._openai_client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": self.SYSTEM_PROMPT},
                    {"role": "user", "content": prompt},
                ],
            )

            # Parse response
            import json

            content = response.choices[0].message.content
            if not content:
                logger.warning("Empty response from AI, using mock")
                return self._generate_mock_poll(event)

            result = json.loads(content)

            return GeneratedPoll(
                question=result["question"],
                choices=result["choices"],
                category=event.category,
                source_event_id=event.id,
                bias_check_passed=result.get("bias_analysis", {}).get("confidence_score", 0) > 0.8,
                bias_analysis=result.get("bias_analysis", {}),
                suggested_duration_hours=24,
            )

        except Exception as e:
            logger.error(f"Failed to generate poll: {e}")
            return None

    def _generate_mock_poll(self, event: NewsEvent) -> GeneratedPoll:
        """Generate a mock poll for development/testing with diverse topics."""
        import random

        # Comprehensive mock questions by category
        mock_questions: dict[str, list[dict[str, str | list[str]]]] = {
            "environment": [
                {
                    "question": "Regarding recent climate discussions, what approach do you think governments should prioritize?",
                    "choices": [
                        "Aggressive emissions targets with economic trade-offs",
                        "Gradual transition balancing economy and environment",
                        "Market-based solutions without government mandates",
                        "Focus on adaptation rather than prevention",
                        "Undecided / Need more information",
                    ],
                },
                {
                    "question": "How should communities address local environmental challenges?",
                    "choices": [
                        "Increased local regulations and enforcement",
                        "Community-led voluntary initiatives",
                        "Public-private partnerships",
                        "Federal intervention and funding",
                        "Focus on education over regulation",
                    ],
                },
                {
                    "question": "What is the most effective way to reduce carbon emissions?",
                    "choices": [
                        "Transition to renewable energy sources",
                        "Carbon pricing and taxation",
                        "Individual lifestyle changes",
                        "Technological innovation",
                        "International cooperation and treaties",
                    ],
                },
            ],
            "technology": [
                {
                    "question": "How should AI technology be regulated?",
                    "choices": [
                        "Strict government oversight and licensing",
                        "Industry self-regulation with guidelines",
                        "Minimal regulation to encourage innovation",
                        "International coordination on standards",
                        "Undecided / Need more information",
                    ],
                },
                {
                    "question": "What concerns you most about social media platforms?",
                    "choices": [
                        "Privacy and data collection",
                        "Misinformation and fake news",
                        "Impact on mental health",
                        "Political polarization",
                        "No major concerns",
                    ],
                },
                {
                    "question": "How should tech companies handle user data?",
                    "choices": [
                        "Users should have complete control and ownership",
                        "Companies should be transparent but self-regulate",
                        "Government should set strict data protection rules",
                        "Data sharing is acceptable for free services",
                        "Case-by-case depending on the service",
                    ],
                },
            ],
            "politics": [
                {
                    "question": "What should be the top priority for government spending?",
                    "choices": [
                        "Healthcare and social services",
                        "Infrastructure and transportation",
                        "Education and job training",
                        "Defense and national security",
                        "Debt reduction and fiscal responsibility",
                    ],
                },
                {
                    "question": "How should elected officials engage with constituents?",
                    "choices": [
                        "Regular town halls and public forums",
                        "Social media and digital engagement",
                        "Work primarily through local representatives",
                        "Focus on legislative work over engagement",
                        "All of the above equally",
                    ],
                },
                {
                    "question": "What approach to political compromise do you prefer?",
                    "choices": [
                        "Leaders should seek bipartisan solutions",
                        "Elected officials should stick to their platform",
                        "Compromise depends on the specific issue",
                        "More direct democracy and public input",
                        "No strong opinion",
                    ],
                },
            ],
            "business": [
                {
                    "question": "What is the most important factor when choosing where to work?",
                    "choices": [
                        "Salary and financial compensation",
                        "Work-life balance and flexibility",
                        "Career growth opportunities",
                        "Company culture and values",
                        "Job security and stability",
                    ],
                },
                {
                    "question": "How should companies approach remote work?",
                    "choices": [
                        "Fully remote options for all eligible roles",
                        "Hybrid model with required office days",
                        "Return to traditional office work",
                        "Let individual teams decide",
                        "Depends on the industry and role",
                    ],
                },
                {
                    "question": "What is the biggest challenge facing small businesses today?",
                    "choices": [
                        "Access to capital and funding",
                        "Competition from large corporations",
                        "Regulatory burden and compliance",
                        "Finding and retaining talent",
                        "Economic uncertainty",
                    ],
                },
            ],
            "health": [
                {
                    "question": "What is the most pressing healthcare issue today?",
                    "choices": [
                        "Cost of healthcare and medications",
                        "Access to quality care",
                        "Mental health services",
                        "Preventive care and wellness",
                        "Healthcare workforce shortages",
                    ],
                },
                {
                    "question": "How should mental health services be improved?",
                    "choices": [
                        "More insurance coverage for mental health",
                        "School-based mental health programs",
                        "Workplace mental health initiatives",
                        "Community mental health centers",
                        "Telehealth and digital solutions",
                    ],
                },
                {
                    "question": "What approach to public health do you support?",
                    "choices": [
                        "Strong government health mandates",
                        "Education and voluntary guidelines",
                        "Local community-based decisions",
                        "Individual choice with minimal intervention",
                        "Science-based policies with flexibility",
                    ],
                },
            ],
            "science": [
                {
                    "question": "Where should scientific research funding be prioritized?",
                    "choices": [
                        "Medical and health research",
                        "Climate and environmental science",
                        "Space exploration",
                        "Technology and computing",
                        "Basic scientific research",
                    ],
                },
                {
                    "question": "How should scientific findings influence policy?",
                    "choices": [
                        "Science should be the primary driver of policy",
                        "Balance scientific input with other factors",
                        "Scientists should advise but not decide",
                        "Depends on the policy area",
                        "Public opinion should take precedence",
                    ],
                },
            ],
            "world": [
                {
                    "question": "What should be the priority in international relations?",
                    "choices": [
                        "Global cooperation and multilateralism",
                        "National interests first",
                        "Regional partnerships and alliances",
                        "Economic relationships and trade",
                        "Human rights and democracy promotion",
                    ],
                },
                {
                    "question": "How should countries address global challenges?",
                    "choices": [
                        "Through international organizations",
                        "Bilateral agreements between countries",
                        "Focus on domestic solutions first",
                        "Public-private global partnerships",
                        "Case-by-case assessment",
                    ],
                },
            ],
            "entertainment": [
                {
                    "question": "How do you prefer to consume entertainment content?",
                    "choices": [
                        "Streaming services at home",
                        "Traditional theaters and venues",
                        "Live events and concerts",
                        "Social media and short-form content",
                        "Mix of all formats",
                    ],
                },
                {
                    "question": "What matters most in entertainment industry practices?",
                    "choices": [
                        "Fair compensation for creators",
                        "Diverse representation",
                        "Quality over quantity",
                        "Affordable access for consumers",
                        "Innovation and new formats",
                    ],
                },
            ],
            "sports": [
                {
                    "question": "What is the biggest issue facing professional sports?",
                    "choices": [
                        "Player salaries and team economics",
                        "Fan experience and engagement",
                        "Health and safety of athletes",
                        "Integrity and fair play",
                        "Access and inclusivity",
                    ],
                },
                {
                    "question": "How should sports address social issues?",
                    "choices": [
                        "Athletes should use their platform to speak out",
                        "Sports should remain neutral",
                        "Organizations should lead initiatives",
                        "Focus on community programs",
                        "Individual choice for athletes and teams",
                    ],
                },
            ],
        }

        # Normalize category to lowercase
        category = event.category.lower()

        # Get questions for category or use general pool
        category_questions = mock_questions.get(category, [])

        # If no category match, pick from a random category
        if not category_questions:
            all_questions = [q for questions in mock_questions.values() for q in questions]
            if all_questions:
                poll_template = random.choice(all_questions)
            else:
                # Ultimate fallback
                poll_template = {
                    "question": f"What is your view on: {event.title}?",
                    "choices": [
                        "Strongly support the described approach",
                        "Somewhat support with reservations",
                        "Neutral / Mixed feelings",
                        "Somewhat oppose",
                        "Strongly oppose",
                    ],
                }
        else:
            # Pick a random question from the category
            poll_template = random.choice(category_questions)

        # Cast to expected types
        question = str(poll_template["question"])
        choices = list(poll_template["choices"]) if isinstance(poll_template["choices"], list) else []

        return GeneratedPoll(
            question=question,
            choices=choices,
            category=event.category,
            source_event_id=event.id,
            bias_check_passed=True,
            bias_analysis={
                "potential_issues": [],
                "mitigations_applied": ["neutral framing", "balanced options"],
                "confidence_score": 0.92,
            },
            suggested_duration_hours=24,
        )

    BIAS_VALIDATION_PROMPT = """You are an expert in detecting bias in poll questions.
Analyze the following poll for any potential bias issues:

QUESTION: {question}

CHOICES:
{choices}

CATEGORY: {category}

Check for:
1. LEADING QUESTIONS: Does the question push toward a particular answer?
2. LOADED LANGUAGE: Does the question use emotionally charged words?
3. FALSE DICHOTOMY: Are nuanced positions missing from the choices?
4. UNBALANCED OPTIONS: Do choices favor one side over another?
5. MISSING PERSPECTIVES: Are major viewpoints unrepresented?
6. PRESUPPOSITIONS: Does the question assume facts not established?

Respond in JSON format:
{{
    "passed": true/false,
    "issues": ["List of specific issues found"],
    "suggestions": ["Specific suggestions for improvement"],
    "confidence": 0.0-1.0
}}"""

    async def validate_poll_bias(
        self,
        poll: GeneratedPoll,
    ) -> dict:
        """
        Validate a poll for potential bias issues.

        Uses a separate AI evaluation to check for:
        - Leading questions
        - Unbalanced answer choices
        - Loaded language
        - Missing perspectives
        """
        await self.initialize()

        # Use AI to validate if available
        if self._openai_client:
            try:
                import json

                choices_text = "\n".join(f"- {c}" for c in poll.choices)
                prompt = self.BIAS_VALIDATION_PROMPT.format(
                    question=poll.question,
                    choices=choices_text,
                    category=poll.category,
                )

                response = await self._openai_client.chat.completions.create(
                    model=settings.FOUNDRY_MODEL_DEPLOYMENT,
                    messages=[
                        {
                            "role": "system",
                            "content": "You are a bias detection expert. Respond only with valid JSON.",
                        },
                        {"role": "user", "content": prompt},
                    ],
                    temperature=0.3,  # Lower temperature for more consistent analysis
                    max_tokens=500,
                )

                result_text = response.choices[0].message.content
                if result_text is None:
                    logger.warning("Empty response from AI for bias validation")
                    return self._heuristic_bias_check(poll)

                # Extract JSON from response
                if "```json" in result_text:
                    result_text = result_text.split("```json")[1].split("```")[0]
                elif "```" in result_text:
                    result_text = result_text.split("```")[1].split("```")[0]

                result = json.loads(result_text.strip())

                passed = result.get("passed", True)
                issues_count = len(result.get("issues", []))
                logger.info(
                    f"Bias validation completed for '{poll.question[:50]}': passed={passed}, issues={issues_count}"
                )

                return result

            except Exception as e:
                logger.error(f"Bias validation failed: {e}")

        # Fallback: basic heuristic checks
        return self._heuristic_bias_check(poll)

    def _heuristic_bias_check(self, poll: GeneratedPoll) -> dict:
        """
        Fallback heuristic bias checking when AI is unavailable.

        Checks for common bias indicators without AI.
        """
        issues = []
        suggestions = []

        # Check for loaded language
        loaded_words = [
            "always",
            "never",
            "must",
            "should",
            "obviously",
            "clearly",
            "everyone knows",
            "radical",
            "extreme",
            "dangerous",
            "crisis",
            "disaster",
            "freedom",
            "liberty",
        ]
        question_lower = poll.question.lower()
        for word in loaded_words:
            if word in question_lower:
                issues.append(f"Potentially loaded language: '{word}'")
                suggestions.append(f"Consider rephrasing to remove '{word}'")

        # Check for yes/no binary (often too simplistic)
        choices_lower = [c.lower() for c in poll.choices]
        if len(poll.choices) == 2 and set(choices_lower) == {"yes", "no"}:
            issues.append("Binary yes/no options may oversimplify the issue")
            suggestions.append("Consider adding nuanced options like 'It depends' or 'Partially'")

        # Check for "undecided" option
        has_undecided = any(
            "undecided" in c.lower() or "unsure" in c.lower() or "other" in c.lower() for c in poll.choices
        )
        if not has_undecided and len(poll.choices) < 5:
            suggestions.append("Consider adding an 'Undecided/Other' option")

        # Check for balanced choice count
        if len(poll.choices) < 3:
            issues.append("Too few choices may not represent all viewpoints")
            suggestions.append("Add more nuanced options")

        passed = len(issues) == 0
        confidence = 0.7 if passed else 0.5  # Lower confidence for heuristic check

        return {
            "passed": passed,
            "issues": issues,
            "suggestions": suggestions,
            "confidence": confidence,
        }

    async def generate_daily_polls(
        self,
        events: list[NewsEvent],
        count: int = 5,
    ) -> list[Poll]:
        """
        Generate the daily set of featured polls.

        Selects diverse events across categories and generates
        unbiased poll questions for each.
        """
        generated_polls = []

        # Ensure category diversity
        categories_used: set[str] = set()
        events_to_use: list[NewsEvent] = []

        for event in sorted(events, key=lambda e: e.relevance_score, reverse=True):
            if event.category not in categories_used and len(events_to_use) < count:
                events_to_use.append(event)
                categories_used.add(event.category)

        # Fill remaining slots if needed
        for event in events:
            if event not in events_to_use and len(events_to_use) < count:
                events_to_use.append(event)

        # Generate polls
        for event in events_to_use:
            generated = await self.generate_poll_from_event(event)
            if generated and generated.bias_check_passed:
                poll = Poll(
                    id=str(uuid4()),
                    question=generated.question,
                    choices=[PollChoice(id=str(i), text=choice, order=i) for i, choice in enumerate(generated.choices)],
                    category=generated.category,
                    source_event=event.title,
                    created_at=datetime.now(timezone.utc),
                    expires_at=datetime.now(timezone.utc) + timedelta(hours=generated.suggested_duration_hours),
                    is_active=True,
                    ai_generated=True,
                    time_remaining_seconds=generated.suggested_duration_hours * 3600,
                )
                generated_polls.append(poll)

        return generated_polls
